query search($search: String!){
  messages(where: {_or: [{ full_name: { _ilike: $search } } { message: { _ilike: $search } } { subject: { _ilike: $search } } { email: { _ilike: $search } } { phone_number: { _ilike: $search } } ]}) {
     id
    user_id
    full_name
    email
    phone_number
    subject
    message
    created_at
    updated_at
  }
}