mutation($id: uuid!, $email: String!, $first_name: String!, $last_name: String!, $date_of_birth: date!, $location: String!,  $phone_number: String!, $profession: String!,  $role: String!, $user_name: String!, $work_place: String!, $description: String!) {
    update_users_by_pk(pk_columns: { id: $id }, _set: { email: $email, first_name: $first_name, date_of_birth: $date_of_birth, last_name: $last_name, location: $location,  phone_number: $phone_number, profession: $profession,  role: $role, user_name: $user_name, work_place: $work_place, description: $description }) {
        id
    }
}
