query MyQuery {
  users(order_by: { full_name: asc }) {
    id
    user_name
    full_name
    sex
    email
    role
    salary
    date_of_entry
    created_at
    updated_at
    attendances(order_by: { created_at: asc }) {
      id
      date
      shift
      time
      created_at
    }
  }
  attendances(order_by: { created_at: asc }) {
    id
    date
    shift
    time
    created_at
  }
}
