query search($search: String!) {
  attendance(
    where: {
      _or: [
        { user: {full_name: { _ilike: $search }} }
      
      
       
      ]
    }
  ) {
    id
    shift
    date
    time
    created_at
    user {
      id
      user_name
      full_name
      role
      salary
      sex
      email
      date_of_entry
    }
  }
}
