mutation RegisterEmployee (
  $user_name: String!
  $email: String!
  $password: String!
  $full_name: String!
  $salary: Int!
  $sex: InsertUsersOneDerivedEnumSexEnum!
  $date_of_entry: date!
  $role: String!
  $phone_number: String!
) {
  RegisterEmployee(
    user_name: $user_name
    password: $password
    full_name: $full_name
    email: $email
    salary: $salary
    sex: $sex
    role: $role
    date_of_entry: $date_of_entry
    phone_number: $phone_number
  ) {
    id
    token
  }
}
