-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."guests" add column "is_suspended" boolean
--  not null default 'false';
