query search($search: String!){
  services(where: {_or: [{ name: { _ilike: $search } } { description: { _ilike: $search } } ]}) {
    id
    user_id
    name
    description
    icon
    created_at
    updated_at
  
  }
}